{"name": "test_failed", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 != 1", "trace": "self = <TestCase.test_0_login.TestLogin object at 0x0000000003E1F630>\n\n    def test_failed(self):\n>       assert  1!=1\nE       assert 1 != 1\n\nTestCase\\test_0_login.py:38: AssertionError"}, "start": 1558344077537, "stop": 1558344077537, "uuid": "5f16c841-a1cb-4f9e-8753-d2b84ad25b4e", "historyId": "98d4ab842603cdfc0380ae0bd8991cba", "fullName": "TestCase.test_0_login.TestLogin#test_failed", "labels": [{"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_0_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "bj_jd-PC"}, {"name": "thread", "value": "6240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_0_login"}]}